apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sporingslogg
  namespace: _NAIS_ENV_
  labels:
    team: integrasjon
spec:
  image: _IMAGE_FULLNAME_
  port: 8088
  secureLogs:
    enabled: false
  replicas:
    min: 2
    max: 4
    cpuThresholdPercentage: 60
  liveness:
    path: /sporingslogg/api/ping
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 60
  readiness:
    path: /sporingslogg/api/ping
    initialDelay: 5
    periodSeconds: 5
    failureThreshold: 60
  resources:
    limits:
      cpu: 400m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi
  secrets: true
      