no.nav.security.jwt:
  issuer.difi:
    discoveryurl: '${VER2_DIFI_TOKEN_CONFIGURATION_URL}'
    accepted_audience: 'nav.no, dev.nav.no'
  issuer.servicebruker:
    discoveryurl: '${SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL}'
    accepted_audience: 'srvpensjon, srvsporingslogg'

kafka:
  sporingslogg:
    topic: ${SPORINGSLOGG_KAFKA_TOPIC}
    groupid: KC-${SPORINGSLOGG_KAFKA_TOPIC}

server:
  error:
    include-message: always

management:
  endpoints:
    health:
      show-details: always
    prometheus:
      enabled: true
    web:
      exposure:
        include: health, info, prometheus

