no.nav.security.jwt:
  issuer.difi:
    discoveryurl: '${DIFI_TOKEN_CONFIGURATION_URL}'
    accepted_audience: 'https://nav.no,https://dev.nav.no,nav.no,dev.nav.no'
  issuer.servicebruker:
    discoveryurl: '${SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL}'
    accepted_audience: 'srvpensjon,srvsporingslogg'

kafka:
  sporingslogg:
    topic: ${SPORINGSLOGG_KAFKA_TOPIC}
    groupid: ${SPORINGSLOGG_KAFKA_GROUP}

server:
  error:
    include-message: always

management:
  endpoints:
    health:
      show-details: always
    metrics:
      enabled: true
    prometheus:
      enabled: true
    web:
      exposure:
        include: prometheus,health,info,metrics
