apiVersion: "nais.io/v1alpha1"
kind: "Application"
metadata:
  name: sporingslogg
  namespace: pensjonsamhandling
  labels:
    team: pensjonsamhandling
spec:
  image: {{ image }}
  port: 8088
  ingresses:
    - "https://sporingslogg.nais.adeo.no"
    - "https://sporingslogg.intern.nav.no"
  secureLogs:
    enabled: false
  replicas:
    min: 1
    max: 1
    cpuThresholdPercentage: 80
  prometheus:
    enabled: true
    path: /sporingslogg/prometheus
  liveness:
    path: /actuator/health/liveness
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 60
  readiness:
    path: /actuator/health/readiness
    initialDelay: 20
    periodSeconds: 5
    failureThreshold: 60
  resources:
    limits:
      cpu: 1000m
      memory: 2024Mi
    requests:
      cpu: 800m
      memory: 1012Mi
  vault:
    enabled: true
    paths:
      - kvPath: /oracle/data/prod/creds/sporingslogg_p-user
        mountPath: /secrets/oracle_creds
      - kvPath: /serviceuser/data/prod/srvsporingslogg
        mountPath: /secrets/serviceuser
  webproxy: true
#  kafka:
#    pool: nav-prod
  env:
    - name: SPRING_PROFILES_ACTIVE
      value: prod
    - name: ENV
      value: p
    - name: DBURL
      value: jdbc:oracle:thin:@a01dbfl043.adeo.no:1521/SPORINGSLOGG_P_HA
    - name: SPORINGSLOGG_KAFKA_TOPIC
      value: aapen-sporingslogg-loggmeldingMottatt
    - name: SPORINGSLOGG_AIVEN_KAFKA_TOPIC
      value: public-sporingslogg-loggmeldingMottatt
    - name: ONPREM_KAFKA_BOOTSTRAP_SERVERS_URL
      value: SASL_SSL://a01apvl00145.adeo.no:8443,a01apvl00146.adeo.no:8443,a01apvl00147.adeo.no:8443,a01apvl00148.adeo.no:8443,a01apvl00149.adeo.no:8443,a01apvl00150.adeo.no:8443
    - name: VER2_DIFI_TOKEN_CONFIGURATION_URL
      value: https://oidc.difi.no/idporten-oidc-provider/.well-known/openid-configuration
    - name: SECURITY_TOKEN_SERVICE_OPENID_CONFIGURATION_URL
      value: https://security-token-service.nais.adeo.no/rest/v1/sts/.well-known/openid-configuration
