name: Bygg og deploy

on:
  push:
    branches:
      - master

jobs:
  tag_build_and_deploy:
    name: 'Build, deploy and tag'
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
      id-token: write
      checks: write
    steps:
      # PULLER REPO
      - name: 'Pull repo'
        uses: actions/checkout@v4

      # JAVA
      - name: 'Java 21'
        uses: actions/setup-java@v3
        with:
          java-version: 21
          distribution: temurin
          cache: 'gradle'

      #
      - name: 'Gradlew bygg og test'
        run: ./gradlew build --stacktrace

      # LOGGIN TO GHCR
      - name: Login to GHCR
        uses: docker/login-action@v2.2.0
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.GITHUB_TOKEN }}

      # SETTER DATO OG COMMIT VARIABEL
      - name: 'Setter dato og hash'
        run: |
          export TZ=CET
          echo "DATE=$(date "+%Y-%m-%d--%H-%M-%S")" >> $GITHUB_ENV
          echo "COMMIT_HASH=$(git rev-parse HEAD)" >> $GITHUB_ENV
      # SETTER IMAGE VARIABEL
      - name: 'Setter Image'
        run: echo "IMAGE=ghcr.io/${{ github.repository }}/sporingslogg:${{ env.DATE }}---${{ env.COMMIT_HASH }}" >> $GITHUB_ENV

      # PUBLISH DOCKER IMAGE
      - name: Build and push docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: ${{ env.IMAGE }}

  DeployToQ2:
    name: Deploy to Q2
    needs: tag_build_and_deploy
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Deploy to Q2
        uses: nais/deploy/actions/deploy@v1
        env:
          "APIKEY": ${{ secrets.NAIS_DEPLOY_APIKEY }}
          "CLUSTER": dev-fss
          "RESOURCE": nais/dev_q2.yaml
          "IMAGE": ${{ env.IMAGE }}

